### ISSUE TITLE
synthetics_create_browser_check_v2  documentation

### ISSUE THREAD

**Issue by aport1996** [splunk/terraform-provider-synthetics#39]
Hello,

For the following documentation (but also the others): https://registry.terraform.io/providers/splunk/synthetics/latest/docs/resources/create_browser_check_v2#nestedblock--test--transactions--steps

We don't see any information on what values we can enter for the various variables that there are.

For example, we don't know what values we can use for keys such as "selector", "selector_type", etc. 

Can you please add this to the terraform documentation, or point us to the right documentation if it exists?

Thank you!

**Comment by greatestusername-splunk** [comment]
Thank you for posting this issue!
Currently the best place to find the acceptable values is from the [api documentation](https://dev.splunk.com/observability/reference/api/synthetics_api_tests/latest#endpoint-createapitest). 

Due to the terraform provider being an interface for the API the provider isn't really the source of truth for acceptable values. That said, it may be possible to specifically add some of the accepted values and a link to the actual API documentation in the terraform provider docs (keeping in mind they will never be the source of truth).

**Comment by kkgthb** [comment]
I volunteered #75 to try to help address this issue.

In `docs/resources/create_browser_check_v2.md`, I:

1. Left all examples of `selector_type` as `id` as before, but added an inline comment at the end of the first example listing all 6 valid `selector_type` values _(`id`, `name`, `xpath`, `css`, `link`, `jspath`)_.
2. Added 6 new "assertion" step `type` examples to cover Documentation example code does not mention the existence of any of the 6 "assertion" step types _(`assert_element_present`, `assert_element_not_present`, `assert_element_visible`, `assert_element_not_visible`, `assert_text_present`, `assert_text_not_present`)_.
